name: dart_lambda
description: A simple Dart project
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  aws_lambda_dart_runtime: 
  uuid: ^3.0.4

dev_dependencies:
  build_runner:
  test: any
  # Add your development dependencies here