AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dart Lambda Function with API Gateway

Resources:
  DartFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      Architectures: 
        - arm64
      CodeUri: lambda.zip
      Runtime: provided.al2
      Handler: hello.ALB
      MemorySize: 512
      Timeout: 10
      Events:
        HttpAny:
          Type: Api
          Properties:
            Path: /v1/{proxy+}
            Method: ANY

Outputs:
  ApiUrlLink:
    Description: URL of the API Gateway
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com